# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Yinghao Pan
tagline:          '潘颖豪'
description:      'Ph.D.  </br> '
url:              https://ian-pan.github.io
baseurl:          #'/blog'
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:          Yinghao Pan
name:           'Yinghao Pan'
email:           <a href="mailto:mail@yinghaopan.com" title="mail@yinghaopan.com">mail@yinghaopan.com</a></br>

paginate:         5
paginate_path:    #'/page:num'
                    # Or '/blog/page:num' if you want to move your index pages
google_analytics:   G-QNGBJ14GNY

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Sidebar link settings
sidebar_home_link:  false
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
